---
title: "Resultados"
output: html_notebook
---

```{r}
library(tidyverse)
library(lubridate)
library(sf)
library(spdep)
library(cowplot)
```


```{r}
load('Resultados_GAM.RData')
metricas_tot_GAM <- metricas_tot %>% mutate(Model='GAMLSS')

mejores_GAM <- sort(metricas_tot_GAM$NIS_95,index.return=T)$ix[1:3] 

nombres_cantones$Canton[mejores_GAM]
peores_GAM <- sort(metricas_tot_GAM$NIS_95,decreasing =T,index.return=T)$ix[1:3] 
nombres_cantones$Canton[peores_GAM]

indices_cantones <- c(mejores_GAM,peores_GAM)

nombres_GAM <- nombres_cantones$Canton[indices_cantones]


indice <- indices_cantones
base_grafico_lista <- function(indice){
  RR_obs <- bases_ent[[indice]] %>%
    dplyr::select(RR)
  fechas <- bases_ent[[indice]] %>% 
    dplyr::select(Year,Month) %>% mutate(fecha=make_date(Year,Month,1))
  base_grafico <- predicciones_in[[indice]] %>% bind_cols(RR_obs) %>%
    mutate(fechas=fechas$fecha,Canton=nombres_cantones$Canton[indice])
  return(base_grafico)
}

base_grafico_GAM <- map_dfr(indice,~base_grafico_lista(.))


base_grafico_lista_2 <- function(indice){
  RR_obs <- bases_test_1[[indice]] %>%
    dplyr::select(RR)
  fechas <- bases_test_1[[indice]] %>% 
    dplyr::select(Year,Month) %>% mutate(fecha=make_date(Year,Month,1))
  predicciones <- data.frame(fit=predicciones_out_1[[indice]])
  quantiles <- data.frame(low = quantiles_out_1[[indice]][1,],
                          up = quantiles_out_1[[indice]][2,])
  base_grafico <- predicciones %>% bind_cols(quantiles) %>%
    bind_cols(RR_obs) %>%
    mutate(fechas=fechas$fecha,Canton=nombres_cantones$Canton[indice])
  return(base_grafico)
}

base_grafico_out_GAM<- map_dfr(indice,~base_grafico_lista_2(.))

load('Resultados_RF.RData')
metricas_tot_RF <- metricas_tot %>% mutate(Model='RF')
metricas_tot <- bind_rows(metricas_tot_RF,metricas_tot_GAM)

mejores_RF <- sort(metricas_tot_RF$NIS_95,index.return=T)$ix[1:3] 
nombres_cantones$Canton[mejores_RF]
peores_RF <- sort(metricas_tot_RF$NIS_95,decreasing = T,index.return=T)$ix[1:3] 
nombres_cantones$Canton[peores_RF]

indices_cantones <- c(mejores_RF,peores_RF)

nombres_RF <- nombres_cantones$Canton[indices_cantones]


indice <- indices_cantones
base_grafico_lista <- function(indice){
  RR_obs <- bases_ent[[indice]] %>%
    dplyr::select(RR)
  fechas <- bases_ent[[indice]] %>% 
    dplyr::select(Year,Month) %>% mutate(fecha=make_date(Year,Month,1))
  base_grafico <- predicciones_in[[indice]] %>% bind_cols(RR_obs) %>%
    mutate(fechas=fechas$fecha,Canton=nombres_cantones$Canton[indice])
  colnames(base_grafico)[1] <- 'fit'
  return(base_grafico)
}

base_grafico_RF <- map_dfr(indice,~base_grafico_lista(.))

base_grafico_lista_2 <- function(indice){
  RR_obs <- bases_test_1[[indice]] %>%
    dplyr::select(RR)
  fechas <- bases_test_1[[indice]] %>% 
    dplyr::select(Year,Month) %>% mutate(fecha=make_date(Year,Month,1))
  predicciones <- data.frame(fit=predicciones_out_1[[indice]])
  quantiles <- data.frame(low = quantiles_out_1[[indice]][1,],
                          up = quantiles_out_1[[indice]][2,])
  base_grafico <- predicciones %>% bind_cols(quantiles) %>%
    bind_cols(RR_obs) %>%
    mutate(fechas=fechas$fecha,Canton=nombres_cantones$Canton[indice])
  return(base_grafico)
}

base_grafico_out_RF<- map_dfr(indice,~base_grafico_lista_2(.))
```


Histograma de las diferencias entre los NIS de ambos algoritmos y diagramas de caja:
```{r}
caja_NIS <- ggplot(data = metricas_tot) +
  geom_boxplot(mapping = aes(y=NIS_95,fill=Model))+
  theme(axis.text.x = element_blank())+
  theme_bw()

caja_NRMSE <- ggplot(data = metricas_tot) +
  geom_boxplot(mapping = aes(y=NRMSE,fill=Model))

D_NIS <- data.frame(D = metricas_tot_RF$NIS_95-metricas_tot_GAM$NIS_95)
histograma_NIS <- ggplot(data = D_NIS)+ 
  geom_histogram(mapping = aes(x = D),bins = 4,fill='white',col=1)+
  theme_bw()

show(caja_NIS)
show(caja_NRMSE)
show(histograma_NIS)

#save_plot('caja_NIS.pdf',plot = caja_NIS)
#caja_NIS 614X352
```

Predicciones en mejores y peores GAM:
```{r}
grafico_out_GAM <- ggplot(data = base_grafico_out_GAM,mapping = aes(x = fechas,y = fit)) + 
  geom_line(col=2)+
  geom_line(mapping = aes(y=RR))+
  geom_ribbon(mapping = aes(ymin = low, ymax = up),fill=2,alpha=0.5) +
  theme_bw()+
  facet_wrap(facets = vars(factor(Canton,levels = nombres_GAM)),ncol = 3,scales = 'free')+
  xlab('Date')+ylab('Relative Risk')
show(grafico_out_GAM)  #grafico_out_GAM 800X457 
#save_plot(filename = 'grafico_out_GAM.pdf',plot = grafico_out_GAM,base_asp = 2.5)
save_plot(filename = 'grafico_out_GAM.png',plot = grafico_out_GAM,base_asp = 2.5)
```

Predicciones en mejores y peores RF:
```{r}
grafico_out_RF <- ggplot(data = base_grafico_out_RF,mapping = aes(x = fechas,y = fit)) + 
  geom_line(col=2)+
  geom_line(mapping = aes(y=RR))+
  geom_ribbon(mapping = aes(ymin = low, ymax = up),fill=2,alpha=0.5) +
  theme_bw()+
  facet_wrap(facets = vars(factor(Canton,levels = nombres_RF)),ncol = 3,scales = 'free')+
  xlab('Date')+ylab('Relative Risk')
show(grafico_out_RF)
#save_plot(filename = 'grafico_out_RF.pdf',plot = grafico_out_RF,base_asp = 2.5)
```

Mapas de Riesgo Relativo:

Tres puntos en un año dado (2015):
```{r}
distritos_st <-st_read('Data/distritos_shape/Distritos_de_Costa_Rica.shp') %>%
  filter(CODIGO!=60110) %>% mutate(CCanton = str_sub(CODIGO,1,3))
cantones_st <- distritos_st %>% group_by(CCanton) %>%
  summarise(geometry = st_union(geometry)) %>%
  ungroup() %>% mutate(CCanton = as.numeric(CCanton))
  
datos_2015_1 <- datos_totales %>% filter(Year==2015,Month==3) %>%
  select(CCanton,RR) %>% full_join(cantones_st,by = 'CCanton') %>%
  st_as_sf() %>% mutate(Mes = '2015-3')

datos_2015_2 <- datos_totales %>% filter(Year==2015,Month==7) %>%
  select(CCanton,RR) %>% full_join(cantones_st,by = 'CCanton') %>%
  st_as_sf() %>% mutate(Mes = '2015-7')

datos_2015_3 <- datos_totales %>% filter(Year==2015,Month==10) %>%
  select(CCanton,RR) %>% full_join(cantones_st,by = 'CCanton') %>%
  st_as_sf() %>% mutate(Mes = '2015-10')

datos_J_1 <- datos_totales %>% filter(Year==2005,Month==7) %>%
  select(CCanton,RR) %>% full_join(cantones_st,by = 'CCanton') %>%
  st_as_sf() %>% mutate(Mes = '2005-7')

datos_J_2 <- datos_totales %>% filter(Year==2010,Month==7) %>%
  select(CCanton,RR) %>% full_join(cantones_st,by = 'CCanton') %>%
  st_as_sf() %>% mutate(Mes = '2010-7')

datos_J_3 <- datos_totales %>% filter(Year==2018,Month==7) %>%
  select(CCanton,RR) %>% full_join(cantones_st,by = 'CCanton') %>%
  st_as_sf() %>% mutate(Mes = '2018-7')


datos_grafico <- bind_rows(datos_2015_1,datos_2015_2,datos_2015_3,
                           datos_J_1,datos_J_2,datos_J_3)

datos_grafico$Mes <- factor(datos_grafico$Mes,
                            levels = c('2015-3','2015-7','2015-10',
                                       '2005-7','2010-7','2018-7'))
RR_grafico <- ggplot(data = datos_grafico,mapping = aes(fill=RR)) +
  geom_sf()+
  facet_wrap(vars(Mes),ncol = 3)+
  theme_bw()+
  scale_fill_gradient(low = 'yellow',high = 'red',na.value = 'white')+
  theme(legend.title = element_blank(),axis.text = element_blank(),
        axis.ticks = element_blank())
RR_grafico
#save_plot(filename = 'RR_maps.pdf',plot = RR_grafico)
#save_plot(filename = 'RR_maps.png',plot = RR_grafico)
#ggsave(filename = 'RR_maps.pdf',RR_grafico)
```


